export const PANELS = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  DASHBOARD_INTRO: "DASHBOARD_INTRO",
  ROUND1_INTRO: "ROUND1_INTRO",
  ROUND2_INTRO: "ROUND2_INTRO",
  ROUND2_OUTRO: "ROUND2_OUTRO",
  ROUND3_INTRO: "ROUND3_INTRO", 
  FINAL: "FINAL",
};
